---
title: Tamika Butler - Portfolio
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  logos:
    title: Logos
    output: true
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
port: 4000
host: 0.0.0.0
safe: false
exclude:
- CNAME
- README.md
- ".gitignore"
permalink: "/:title"
gems:
- jekyll-seo-tag
lsi: false
markdown: kramdown
keywords: Tamika Butler, Social Justice, Consulting, Speaking
description: Tamika is the Executive Director of the Los Angeles Neighborhood Land
  Trust.
source_link: https://tamikabutler.com
favicon: img/favicon.ico
touch_icon: img/apple-touch-icon.png
logo: "/uploads/HeaderHero.png"
google_analytics_key: UA-49607422-1
colors:
  black: "#111111"
  white: "#f8f8f8"
  blue: "#49a7e9"
  green: "#9bcf2f"
  purple: "#c869bf"
  orange: "#fab125"
  turquoise: "#0fbfcf"
kramdown:
  auto_ids: false
training: 'As your trainer, Tamika will combine her diverse background as an employment
  lawyer, nonprofit leader, and industry innovator on diversity and inclusion to take
  your team through a series of interactive exercises towards changing culture and
  deep growth.  Tamika will challenge your team, while working at your pace as people
  learn complex ideas, build team cohesion, and identify shared goals. Tamika has
  extensive experience facilitating workshops, meetings, and retreats in the private,
  public, and nonprofit sectors and will work with you before and after the training
  to make sure the training fits your specific organizational needs and includes concrete
  next steps.

'
consulting: 'As your consultant, Tamika will help you and your organization push beyond
  the comfort of your status quo. Working with you, Tamika will assess your needs,
  identify areas of strength and areas for growth, and help tailor a unique action
  plan for your organization to move from diversity to inclusion and fight inequity
  and injustice.

'
speaking: 'As a speaker at your event or meeting, Tamika will use her unique blend
  of charisma, humor, and direct bluntness to inspire the room. As a nationally renowned
  speaker, Tamika will listen to your objectives and put together a speech specifically
  for your event. Tamika employs her personal stories of successes and setbacks to
  bring people in and connect intimately with groups of any size and ensure that people
  leave the room thinking differently and challenging themselves to stay engaged.

'
url: https://tamikabutler.com
